name: Bug Report
description: File a Bug Report.
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: |
        To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: This is not a support issue or a question. For support, questions, or comments, visit [Byte Lobster Discussions](https://github.com/yycorcino/byte-lobster/discussions).
          required: true
        - label: I performed a [cursory search of the issue tracker](https://github.com/yycorcino/byte-lobster/issues) to avoid opening a duplicate issue.
          required: true
        - label: I checked the [documentation](https://github.com/yycorcino/byte-lobster/wiki) to understand that the issue I am reporting is not normal behavior.
          required: true

  - type: checkboxes
    attributes:
      label: I tried to reproduce the issue when...
      options:
        - label:  refreshing the browser.
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Description of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Provide as much detail as possible. We must be able to reproduce to investigate.
      placeholder: |
        1. [Go to '...']
        2. [Click on '....']
        3. [Scroll down to '....']
        4. [See error]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Behavior
      description: What happened?
    validations:
      required: true

  - type: input
    attributes:
      label: Browser Name and Version
    validations:
      required: true